const initials = [];
const countries = [
  "Caribbean Netherlands",
  "Guinea-Bissau",
  "Maldives",
  "Cuba",
  "Oman",
  "Lebanon",
  "Slovakia",
  "Lesotho",
  "Marshall Islands",
  "Aruba",
  "South Sudan",
  "Greenland",
  "Isle of Man",
  "Faroe Islands",
  "Svalbard and Jan Mayen",
  "Mongolia",
  "Mali",
  "Austria",
  "Comoros",
  "Somalia",
  "Cook Islands",
  "Malawi",
  "Micronesia",
  "United States",
  "Pitcairn Islands",
  "Rwanda",
  "Belize",
  "Egypt",
  "Bolivia",
  "Nicaragua",
  "Madagascar",
  "Saint Lucia",
  "Republic of the Congo",
  "Tonga",
  "Jordan",
  "Vanuatu",
  "Yemen",
  "French Guiana",
  "South Africa",
  "Sweden",
  "Antarctica",
  "China",
  "Myanmar",
  "Paraguay",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Kyrgyzstan",
  "Algeria",
  "United States Virgin Islands",
  "Falkland Islands",
  "Liechtenstein",
  "Philippines",
  "Gabon",
  "Bouvet Island",
  "Peru",
  "Fiji",
  "Panama",
  "Sri Lanka",
  "Monaco",
  "Cocos (Keeling) Islands",
  "Nigeria",
  "São Tomé and Príncipe",
  "Slovenia",
  "Dominican Republic",
  "DR Congo",
  "Sudan",
  "Mayotte",
  "Tunisia",
  "Montserrat",
  "United Arab Emirates",
  "Mauritania",
  "Syria",
  "Bhutan",
  "British Indian Ocean Territory",
  "Libya",
  "Western Sahara",
  "Jersey",
  "Burundi",
  "Ivory Coast",
  "Croatia",
  "Ghana",
  "Angola",
  "Liberia",
  "Papua New Guinea",
  "Niue",
  "Nepal",
  "Martinique",
  "Gambia",
  "Guyana",
  "Vatican City",
  "Bulgaria",
  "Jamaica",
  "Timor-Leste",
  "Colombia",
  "Northern Mariana Islands",
  "Central African Republic",
  "Nauru",
  "French Southern and Antarctic Lands",
  "Sierra Leone",
  "French Polynesia",
  "Bangladesh",
  "Cameroon",
  "Palau",
  "Tanzania",
  "Bosnia and Herzegovina",
  "Iran",
  "Latvia",
  "Gibraltar",
  "Anguilla",
  "Guatemala",
  "Cape Verde",
  "Grenada",
  "Vietnam",
  "Bermuda",
  "British Virgin Islands",
  "Christmas Island",
  "Poland",
  "Iraq",
  "Botswana",
  "South Korea",
  "United Kingdom",
  "Israel",
  "Morocco",
  "Spain",
  "Togo",
  "Sint Maarten",
  "Qatar",
  "Mexico",
  "American Samoa",
  "New Caledonia",
  "Tokelau",
  "Guadeloupe",
  "Equatorial Guinea",
  "Antigua and Barbuda",
  "Kuwait",
  "Argentina",
  "India",
  "Saint Barthélemy",
  "Romania",
  "Puerto Rico",
  "Serbia",
  "Laos",
  "Cyprus",
  "Denmark",
  "Belgium",
  "Saint Kitts and Nevis",
  "Åland Islands",
  "Switzerland",
  "Hungary",
  "North Macedonia",
  "Zambia",
  "Australia",
  "Malaysia",
  "Finland",
  "Niger",
  "Canada",
  "Greece",
  "North Korea",
  "Uganda",
  "United States Minor Outlying Islands",
  "Lithuania",
  "Bahrain",
  "Barbados",
  "Cambodia",
  "Suriname",
  "Brunei",
  "Eswatini",
  "Seychelles",
  "Albania",
  "Czechia",
  "Samoa",
  "Uruguay",
  "Luxembourg",
  "Palestine",
  "South Georgia",
  "Norway",
  "Chile",
  "Curaçao",
  "Chad",
  "Tajikistan",
  "Tuvalu",
  "Venezuela",
  "Uzbekistan",
  "Norfolk Island",
  "Mozambique",
  "Georgia",
  "Afghanistan",
  "Brazil",
  "Haiti",
  "Portugal",
  "Guinea",
  "Malta",
  "Costa Rica",
  "Hong Kong",
  "Netherlands",
  "Thailand",
  "Guam",
  "Cayman Islands",
  "Senegal",
  "Pakistan",
  "Ecuador",
  "Kenya",
  "El Salvador",
  "Ireland",
  "Solomon Islands",
  "Benin",
  "Dominica",
  "Djibouti",
  "Turks and Caicos Islands",
  "Eritrea",
  "Taiwan",
  "Saint Pierre and Miquelon",
  "Ukraine",
  "Indonesia",
  "Moldova",
  "Mauritius",
  "Turkmenistan",
  "Trinidad and Tobago",
  "Réunion",
  "Japan",
  "Montenegro",
  "Russia",
  "Germany",
  "Guernsey",
  "Kazakhstan",
  "Saint Martin",
  "Saint Vincent and the Grenadines",
  "Wallis and Futuna",
  "France",
  "Honduras",
  "Italy",
  "Estonia",
  "Turkey",
  "Bahamas",
  "Burkina Faso",
  "Heard Island and McDonald Islands",
  "Saudi Arabia",
  "Andorra",
  "Kosovo",
  "Macau",
  "New Zealand",
  "Zimbabwe",
  "Ethiopia",
  "Azerbaijan",
  "Singapore",
  "Iceland",
  "Armenia",
  "Belarus",
  "Kiribati",
  "San Marino",
  "Namibia",
];

const countriesInitial = countries.map((country) => country.substring(0, 1));
countriesInitial.forEach((value) => {
  if (!initials.includes(value)) {
    initials.push(value);
  }
});

export { countries, initials };
